export const INITIAL_VEHICLES = [
  {
    id: 'c1',
    title: '2024 Porsche 911 GT3 RS',
    slug: '2024-porsche-911-gt3-rs',
    price: 27500000,
    condition: 'NEW',
    mileage: 120, // KM
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    bodyType: 'Coupe',
    engineSize: '4.0L Flat-6',
    power: 518, // HP
    torque: 465,
    groundClearance: 100,
    safetyRating: 5,
    year: 2024,
    description: 'The Porsche 911 GT3 RS is designed for maximum track performance. Features a high-revving naturally aspirated engine, motorsport-derived active aerodynamics, and sophisticated lightweight construction.',
    images: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&q=80&w=800,https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800',
    colorOptions: 'Signal Green,Guards Red,Chalk',
    featured: true,
    sellerId: 'dealer_apex',
    brandId: 'brand_porsche',
    modelId: 'model_911',
    brandName: 'Porsche',
    modelName: '911 GT3 RS',
    sellerName: 'Apex Motors India',
    sellerPhone: '+91 98888 88888',
    sellerCity: 'Mumbai',
    sellerRole: 'DEALER',
    status: 'APPROVED'
  },
  {
    id: 'c2',
    title: '2023 Tesla Model S Plaid',
    slug: '2023-tesla-model-s-plaid',
    price: 13500000,
    condition: 'USED',
    mileage: 8500, // KM
    transmission: 'AUTOMATIC',
    fuelType: 'ELECTRIC',
    bodyType: 'Sedan',
    engineSize: 'Tri-Motor Electric',
    power: 1020, // HP
    torque: 1420,
    groundClearance: 115,
    safetyRating: 5,
    year: 2023,
    description: 'The ultimate electric performance sedan. Features 1020 peak horsepower, tri-motor all-wheel drive, carbon-sleeved rotors, and torque vectoring. Impeccable condition, single owner.',
    images: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&q=80&w=800,https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&q=80&w=800',
    colorOptions: 'Solid Black,Pearl White,Ultra Red',
    featured: true,
    sellerId: 'seller_vikram',
    brandId: 'brand_tesla',
    modelId: 'model_s',
    brandName: 'Tesla',
    modelName: 'Model S Plaid',
    sellerName: 'Vikram Singh',
    sellerPhone: '+91 97777 77777',
    sellerCity: 'Bengaluru',
    sellerRole: 'INDIVIDUAL_SELLER',
    status: 'APPROVED'
  },
  {
    id: 'c3',
    title: '2024 BMW i7 xDrive60',
    slug: '2024-bmw-i7-xdrive60',
    price: 21500000,
    condition: 'NEW',
    mileage: 50,
    transmission: 'AUTOMATIC',
    fuelType: 'ELECTRIC',
    bodyType: 'Sedan',
    engineSize: 'Dual-Motor Electric',
    power: 536, // HP
    torque: 745,
    groundClearance: 136,
    safetyRating: 5,
    year: 2024,
    description: 'The all-electric luxury sedan combining premium performance with futuristic tech. Includes the ultra-wide 31.3" rear Theatre Screen, executive lounge seating, and BMW xDrive dual-motor architecture.',
    images: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=800,https://images.unsplash.com/photo-1607853202273-797f1c22a38e?auto=format&fit=crop&q=80&w=800',
    colorOptions: 'Oxide Grey,Mineral White,Black Sapphire',
    featured: true,
    sellerId: 'dealer_apex',
    brandId: 'brand_bmw',
    modelId: 'model_i7',
    brandName: 'BMW',
    modelName: 'i7 xDrive60',
    sellerName: 'Apex Motors India',
    sellerPhone: '+91 98888 88888',
    sellerCity: 'Mumbai',
    sellerRole: 'DEALER',
    status: 'APPROVED'
  },
  {
    id: 'c4',
    title: '2023 Mercedes-Benz G-Class G 400d AMG Line',
    slug: '2023-mercedes-benz-g-class-g-400d-amg-line',
    price: 25500000,
    condition: 'CERTIFIED_PRE_OWNED',
    mileage: 14000,
    transmission: 'AUTOMATIC',
    fuelType: 'DIESEL',
    bodyType: 'SUV',
    engineSize: '3.0L Inline-6 Turbo',
    power: 326, // HP
    torque: 700,
    groundClearance: 241,
    safetyRating: 5,
    year: 2023,
    description: 'An icon of adventure and luxury. Featuring standard three differential locks, premium AMG body configurations, high-end Nappa leather, and robust 700 Nm diesel torque for off-road excellence.',
    images: 'https://images.unsplash.com/photo-1520050206274-a1ae446cb3cc?auto=format&fit=crop&q=80&w=800,https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=800',
    colorOptions: 'Obsidian Black,Emerald Green',
    featured: false,
    sellerId: 'dealer_apex',
    brandId: 'brand_mercedes',
    modelId: 'model_gclass',
    brandName: 'Mercedes-Benz',
    modelName: 'G-Class G 400d',
    sellerName: 'Apex Motors India',
    sellerPhone: '+91 98888 88888',
    sellerCity: 'Mumbai',
    sellerRole: 'DEALER',
    status: 'APPROVED'
  },
  {
    id: 'c5',
    title: '2022 Mahindra Thar LX Diesel Manual',
    slug: '2022-mahindra-thar-lx-diesel-manual',
    price: 1550000,
    condition: 'USED',
    mileage: 24000,
    transmission: 'MANUAL',
    fuelType: 'DIESEL',
    bodyType: 'SUV',
    engineSize: '2.2L mHawk',
    power: 130, // HP
    torque: 300,
    groundClearance: 226,
    safetyRating: 4,
    year: 2022,
    description: 'The ideal off-road SUV for India. Features shift-on-the-fly 4WD transfer case, mechanically locking rear differential, independent front suspension, and premium hardtop roof configurations.',
    images: 'https://images.unsplash.com/photo-1669818420387-a2f07efd8fe0?auto=format&fit=crop&q=80&w=800',
    colorOptions: 'Napoli Black,Red Rage,Aquamarine',
    featured: false,
    sellerId: 'seller_vikram',
    brandId: 'brand_mahindra',
    modelId: 'model_thar',
    brandName: 'Mahindra',
    modelName: 'Thar LX',
    sellerName: 'Vikram Singh',
    sellerPhone: '+91 97777 77777',
    sellerCity: 'Alwar',
    sellerRole: 'INDIVIDUAL_SELLER',
    status: 'APPROVED'
  }
]

export const INITIAL_BLOGS = [
  {
    id: 'b1',
    title: 'Top 5 Luxury Electric Vehicles to Buy in India in 2026',
    slug: 'top-5-luxury-evs-india-2026',
    content: 'As electric vehicles dominate the luxury segment, we evaluate the best models currently available in India. From the dual-screen experience of the BMW i7 to the speed parameters of the Porsche Taycan, we break down power outputs, range configurations, and charging setups...',
    image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&q=80&w=800',
    createdAt: '2026-06-15T12:00:00Z'
  },
  {
    id: 'b2',
    title: 'The Porsche 911 GT3 RS: Track Performance Redefined',
    slug: 'porsche-911-gt3-rs-review-track',
    content: 'The GT3 RS is Porsche’s purebred track machine disguised in street license plates. With active drag reduction system (DRS) aerodynamics and a 4.0L naturally aspirated flat-6 howling at 9,000 RPM, it pushes the boundaries of internal combustion engineering...',
    image: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&q=80&w=800',
    createdAt: '2026-07-02T12:00:00Z'
  }
]
